sudo: required

language: generic

services:
  - docker

script:
  - docker-compose build app
  - docker-compose run test

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push jonathanost/url-shortener;
    docker tag jonathanost/url-shortener jonathanost/url-shortener:$TRAVIS_COMMIT;
    docker push jonathanost/url-shortener:$TRAVIS_COMMIT;
    fi

branches:
  only:
    - master
